### ISSUE TITLE
Nancy.Swagger module failing to compile in OSX 10.9.2

### ISSUE THREAD

**Issue by cchrisman** [OmniSharp/omnisharp-server#171]
Grabbing latest and compiling, I am getting some build errors.  Reverting to f60f0fe432d12f1bf3a6af908de2ef28ef6b3cba (i.e. pre-swagger) builds without error.

<pre>
Build FAILED.
Errors:

/Users/cchrisman/.vim/bundle/Omnisharp/server/OmniSharp.sln (default targets) ->
(Build target) ->
/Users/cchrisman/.vim/bundle/Omnisharp/server/OmniSharp/OmniSharp.csproj (default targets) ->
/Library/Frameworks/Mono.framework/Versions/2.10.11/lib/mono/4.0/Microsoft.CSharp.targets (CoreCompile target) ->

	AutoComplete/Metadata/AutoCompleteMetadataModule.cs(11,53): error CS0584: Internal compiler error: Method not found: 'Nancy.Swagger.SwaggerExtensions.AsSwagger'.
	AutoComplete/Metadata/AutoCompleteMetadataModule.cs(11,53): error CS0266: Cannot implicitly convert type `object' to `Nancy.Swagger.SwaggerRouteData'. An explicit conversion exists (are you missing a cast?)
	AutoComplete/Metadata/AutoCompleteMetadataModule.cs(11,53): error CS1662: Cannot convert `lambda expression' to delegate type `System.Func<Nancy.Routing.RouteDescription,Nancy.Swagger.SwaggerRouteData>' because some of the return types in the block are not implicitly convertible to the delegate return type
	Build/Metadata/BuildCommandMetadataModule.cs(10,53): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	Build/Metadata/BuildCommandMetadataModule.cs(15,52): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	CheckAliveStatus/Metadata/CheckAliveStatusMetadataModule.cs(10,57): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	CheckReadyStatus/Metadata/CheckReadyStatusMetadataModule.cs(11,57): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	CodeActions/Metadata/FixUsingsMetadataModule.cs(11,50): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	CodeActions/Metadata/GetCodeActionsMetadataModule.cs(11,55): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	CodeActions/Metadata/RunCodeActionMetadataModule.cs(10,54): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	CodeFormat/Metadata/CodeFormatMetadataModule.cs(10,51): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	CodeIssues/Metadata/CodeIssuesMetadataModule.cs(12,54): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	CodeIssues/Metadata/CodeIssuesMetadataModule.cs(18,53): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	CurrentFileMembers/Metadata/CurrentFileMembersAsTreeMetadataModule.cs(10,65): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	CurrentFileMembers/Metadata/CurrentFileMembersAsFlatMetadataModule.cs(12,65): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	CurrentFileMembers/Metadata/CurrentFileTopLevelTypesMetadataModule.cs(12,65): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	FindSymbols/Metadata/FindSymbolsMetadataModule.cs(11,52): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	FindTypes/Metadata/FindTypesMetadataModule.cs(11,50): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	FindUsages/Metadata/FindUsagesMetadataModule.cs(11,51): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	GotoFile/Metadata/GotoFileMetadataModule.cs(11,49): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	GotoImplementation/Metadata/GotoImplementationMetadataModule.cs(11,60): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	GotoRegion/Metadata/GotoRegionMetadataModule.cs(11,51): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	LookupAllTypes/Metadata/LookupAllTypesMetadataModule.cs(10,55): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	Overrides/Metadata/GetOverrideTargetsMetadataModule.cs(11,59): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	Overrides/Metadata/RunOverrideTargetMetadataModule.cs(10,58): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	ProjectManipulation/AddReference/Metadata/AddReferenceMetadataModule.cs(10,53): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	ProjectManipulation/AddToProject/Metadata/AddToProjectMetadataModule.cs(10,53): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	ProjectManipulation/RemoveFromProject/Metadata/RemoveFromProjectMetadataModule.cs(10,58): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	ReloadSolution/Metadata/ReloadSolutionMetadataModule.cs(10,55): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	Rename/Metadata/RenameMetadataModule.cs(10,47): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	SemanticErrors/Metadata/SemanticErrorsMetadataModule.cs(11,55): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	StopServer/Metadata/StopServerMetadataModule.cs(10,51): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	SyntaxErrors/Metadata/CodeCheckMetadataModule.cs(11,50): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	SyntaxErrors/Metadata/SyntaxErrorsMetadataModule.cs(11,53): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	GotoDefinition/Metadata/GotoDefinitionMetadataModule.cs(10,55): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	TypeLookup/Metadata/TypeLookupMetadataModule.cs(10,51): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)
	UpdateBuffer/Metadata/UpdateBufferMetadataModule.cs(11,53): error CS1061: Type `Nancy.Routing.RouteDescription' does not contain a definition for `AsSwagger' and no extension method `AsSwagger' of type `Nancy.Routing.RouteDescription' could be found (are you missing a using directive or an assembly reference?)

	 0 Warning(s)
	 37 Error(s)
</pre>

**Comment by cchrisman** [comment]
Running 'nuget restore' as a step immediately after cloning the repo fixed this issue.
